### ISSUE TITLE
Add and update covers.

### ISSUE THREAD

**Issue by bwhm** [Joystream/design#6]
For the [Joystream repo](https://github.com/Joystream/joystream)
 - [x] Grey "Meetings"
 - [x] Grey "Testnet Releases" (maybe)
 - [x] Grey "Testnet Planning"
 - [x] Grey "Github Policy" (maybe)
 - [x] Black "Testnets"
 - [x] Black "Live OKR"
---
 - [ ] Black "Rome" [example]()https://github.com/Joystream/joystream/tree/master/testnets/acropolis)

Other Repos:

 - [x] Black "Communications"
 - [x] Grey "Blog" 
 - [ ] Black "Whitepaper" [link](https://github.com/Joystream/whitepaper)
 - [ ] Black "Pioneer" [link](https://github.com/Joystream/apps)
 - [ ] Black "Website" [link](https://github.com/Joystream/joystream-website)

**Comment by bedeho** [comment]
Can we close this?

**Comment by bwhm** [comment]
@bedeho @TomiNadratowski 
Not yet, but I will add checkmarks to show outstanding.

**Comment by bedeho** [comment]
Done.
