### ISSUE TITLE
Social Media Cards

### ISSUE THREAD

**Issue by bwhm** [Joystream/design#7]
We need working twitter (and facebook?) cards for:

:one: joystream.org website
This could just be the simple "Joystream" logo, white on black. (.svg and .png in this repo). The code for this should already be there, but I think the image is gone!

:two: blog
This could either be the same logo, with a smaller ".blog" below, or something like what you see on the blog header. (we have an .svg if you need)

:three: [pioneer app](https://github.com/Joystream/apps)
Here, we can either use the same as for joystream.org, only with a subtitle like "Join the testnet", or the athens cover with the same subtitle. At some point, we should make a logo for the app, but not the top priority.

**Comment by bedeho** [comment]
This should not be here, split it up for the corresponding repository, but work these cards cannot commence before the brand identity work has been completed.
