### ISSUE TITLE
Finalise Visual Brand Idenity

### ISSUE THREAD

**Issue by bedeho** [Joystream/design#9]
**Notice: This is a very sloppy description of a problem and corresponding project, which may take some time to narrow down. Only take this as a starting point for an iterative process.**

# Problems

The Joystream visual brand identity is incomplete and undefined, leading to problems in the visual communication with our audience across all of our communication channels, products and messages.

Here is a list of some of our problems currently

## Logomark

We literally are using two separate logo marks simultaneously, a "J" and an elephant. We no longer want to use the elephant, as it does not make sense with our current brand identity and vision, and we require a new set of logo marks that work with our existing wordmark.

Trying to avoid using the elephant logo mark has forced us to use the wordmark in places where it does not make sense, such as

### Github organization 

https://github.com/Joystream

<img width="387" alt="Screenshot 2019-04-19 at 13 42 58" src="https://user-images.githubusercontent.com/437292/57476180-4d5b4a00-7296-11e9-97cf-9bfac6ee42c0.png">

### Twitter account logo

https://twitter.com/joystreamapp

<img width="213" alt="Screenshot 2019-04-19 at 11 41 00" src="https://user-images.githubusercontent.com/437292/57476195-53512b00-7296-11e9-9af6-9442bd1ac3d3.png">

### blog

https://blog.joystream.org/ Arguably this could have use the textmark, as the website itself does.

<img width="160" alt="Screenshot 2019-04-19 at 14 18 43" src="https://user-images.githubusercontent.com/437292/57473685-b17b0f80-7290-11e9-9b80-ddc7075fc71d.png">

### Pioneer application

<img width="186" alt="Screenshot 2019-05-10 at 10 55 42" src="https://user-images.githubusercontent.com/437292/57523087-4f6bea00-7324-11e9-8855-39c7b487f6ba.png">

Here are examples of the mixed usage of logomarks.

### Polkadot Telemetry

https://telemetry.polkadot.io/#/Joystream%20Testnet%20v2

<img width="136" alt="Screenshot 2019-05-10 at 10 57 00" src="https://user-images.githubusercontent.com/437292/57523540-855d9e00-7325-11e9-8bf4-0dbc5c778b8d.png">

### Rocket.chat

<img width="56" alt="Screenshot 2019-04-20 at 20 19 42" src="https://user-images.githubusercontent.com/437292/57472520-e6d22e00-728d-11e9-8c13-9a979515efe6.png">

### Browser tab

<img width="86" alt="Screenshot 2019-04-19 at 11 42 42" src="https://user-images.githubusercontent.com/437292/57472546-f6ea0d80-728d-11e9-8ad0-86295009d10c.png">

### Jsgenesis.com footer

<img width="242" alt="Screenshot 2019-04-19 at 15 10 18" src="https://user-images.githubusercontent.com/437292/57472535-f05b9600-728d-11e9-9d32-fd20032b93b9.png">

### Email newsletter email capture screen

<img width="619" alt="Screenshot 2019-04-19 at 21 10 46" src="https://user-images.githubusercontent.com/437292/57472525-e9348800-728d-11e9-82dc-a8e50e86f7c1.png">

### Testnet Faucet

On https://testnet.joystream.org/faucet

<img width="1091" alt="Screenshot 2019-05-09 at 20 13 10" src="https://user-images.githubusercontent.com/437292/57476467-ec804180-7296-11e9-9caa-f4564f8938d2.png">

# Missing social media covers

We are just using random things, such as

### Twitter account

<img width="1678" alt="Screenshot 2019-04-19 at 11 41 06" src="https://user-images.githubusercontent.com/437292/57476390-c2c71a80-7296-11e9-9ef7-d37301f5f7d4.png">

### Reddit

<img width="1679" alt="Screenshot 2019-04-19 at 11 42 19" src="https://user-images.githubusercontent.com/437292/57473679-ac1dc500-7290-11e9-88a3-cc8141973de1.png">

# Twitter post covers

Here there are many problems. 

## Inconsistency

There is no consistency in the 

- **Background color:**
  - The background colors are not part of the visual brand identity in any recognizable way
  - Background colors are chosen arbitrarily, without thought of how they work with the content or in the context of a twitter feed.
- **Typography:** 
  - The typeface is varied
  - Capitalization is arbitrary
  - Styling, such a bold+italix is arbitrary
  - Positioning and line breaks are arbitrary
- **Layout used:**
  - Some have just an illustration, others have text+illustration, without any system as to why and when

<img width="180" alt="twitter-coulmn" src="https://user-images.githubusercontent.com/437292/57473547-5812e080-7290-11e9-8ae5-add074975573.png">

## Low production quality

- At times a cover has been constructed at one resolution, e.g. originally for the blog, and then been scaled down after being rasterized, leading to very unattractive results. 

<img width="518" alt="Screenshot 2019-04-19 at 11 41 41" src="https://user-images.githubusercontent.com/437292/57473665-a32cf380-7290-11e9-8b73-e58a6e6e68b8.png">

- High detail illustrations from one context are simply scaled down, leading to making it hard to understand

<img width="520" alt="Screenshot 2019-05-10 at 09 32 49" src="https://user-images.githubusercontent.com/437292/57523199-a1ad0b00-7324-11e9-98ff-6062110cba79.png">

## Complex imagery

The imagery chosen is too complex, e.g. "From Sparta to Athens" or "The Sack of Sparta". It is not likely that many in the audience are able to decipher how it matches the message of the post. Instead proper usage of text would greatly aid the communication, and lowering requirements on imagery.

<img width="368" alt="Screenshot 2019-05-09 at 20 14 47" src="https://user-images.githubusercontent.com/437292/57514770-710fa600-7311-11e9-8319-8839edd76e4b.png">

# Lack of explicit rules for images and photographies

These examples from the blog show that we have good rules on what imagery can be included, which leads to low quality and inconsistent communication.

<img width="640" alt="Screenshot 2019-05-10 at 13 18 43" src="https://user-images.githubusercontent.com/437292/57523773-2ea49400-7326-11e9-83e7-25f3063b1638.png">

<img width="293" alt="Screenshot 2019-05-10 at 13 19 22" src="https://user-images.githubusercontent.com/437292/57523801-3feda080-7326-11e9-86be-7f0f590b9304.png">

<img width="617" alt="Screenshot 2019-05-10 at 13 19 59" src="https://user-images.githubusercontent.com/437292/57523838-5a277e80-7326-11e9-88dd-2584d1d35413.png">

# Blog covers 

Blog covers again have complex imagery which does not communicate effectively, and reuses illustratations meant for other purposes. Simply assembling mulitple illustrations is not an effective way of conveying the prupose of a post. 

<img width="1091" alt="Screenshot 2019-04-19 at 14 20 10" src="https://user-images.githubusercontent.com/437292/57473918-39611980-7291-11e9-9617-ab3ec61149ea.png">

<img width="1075" alt="Screenshot 2019-04-19 at 14 21 01" src="https://user-images.githubusercontent.com/437292/57473926-3e25cd80-7291-11e9-89f7-3a25fd4f4f17.png">

Also, as for the twitter covers, the lack of any system in the background colors degrades clarity.

<img width="326" alt="Screenshot 2019-04-19 at 14 19 02" src="https://user-images.githubusercontent.com/437292/57475448-a88c3d00-7294-11e9-8dcf-997a8751e0dc.png">

# Blog images

Blog imagery is abstract and unclear, and often just reuses existing assets without much care.

<img width="649" alt="Screenshot 2019-05-10 at 13 23 21" src="https://user-images.githubusercontent.com/437292/57524014-e0dc5b80-7326-11e9-865d-e2a4ed0f1cad.png">

<img width="458" alt="Screenshot 2019-04-19 at 14 20 18" src="https://user-images.githubusercontent.com/437292/57475401-93171300-7294-11e9-8c52-21d2ffe15507.png">

# Brand

Please review the new brand profile description [here](https://github.com/Joystream/design).

# Deliverables

## Brand style guide

A new complete brand style guide document (in markdown) which covers

- Logo usage guidelines: positioning, backgrounds, etc.
- Key colors
- Additional color palette options
- Typefaces
- Typographic treatments
- Consistent photo style
- Consistent illustration style
- Consistent icon style
- Written voice: **We will write this** 
- Animation guidelines

We have some old stuff on this on Figma, but its not in the form of a full document, and its also not all worth keeping, e.g. some of the color choices are no longer appropriate.  Here are examples of brand style guides we think work well

- https://issuu.com/joaodiogo/docs/frv-brand-guidelines-_final_
- https://www.behance.net/gallery/52871879/Aeromexico-Brand-Identity
- https://issuu.com/lindsayclarke/docs/wolf_circus_style_guide 
- https://issuu.com/corinnealexandra/docs/bas-brandguide
- https://developer.spotify.com/branding-guidelines/
- Logo guidelines only: https://brand.netflix.com/en/assets/brand-logo/ 
- Multiple design systems in one page 
https://designsystemsrepo.com/design-systems/
- Full visual identity: https://www.mckinsey.com/about-us/overview/our-new-identity

### New logoes

A new set of logoes which work with our word mark is required, along with a description for how placement and usage should be done. There should be multiple versions of the logo for multiple resolutions, perhaps with different levle of detail. Here are the contexts in which it may be used.

- Website tab icon
- Email newsletters
- Slide presentations
- Twitter icon
- Twitter cover
- Facebook icon
- Rocketchat icon
- Telegram icon
- Desktop application icon: (tray, bar, dock)
- Website
- Email signature
- Letterhead
- Hoodies/tshirts

Again, its critical that there is an explicit usage policy for how they are to be used.

## Icon set

We would like a light weight general purpose line icon set which covers lots of general purpose needs, including having icons associated with our roles, networks etc. Icons must be vector format, and must come in two versions

- line version
- negative lines on solid background circle 

## Communication templates

Our communication happens primarily over 

- Newsletter
- Blog
- Twitter 

For each, we need a set of well defined templates for the following messages, which address all problems outlined above.

- General message
- Announcement of a testnet
- Announcement of completed specification
- Announcement of the incentives
- Announcement of a testnet going live

One idea we would like to be explored is if all communication associated with a givne testnet can include some standard branding for that testnet, e.g. a tiled logomark for that testnet in background surfaces.

### Newsletter

Here we need a full layout for each case, which is also responsive.

### Blog

Here we need a cover photo (with the correct dimensions) which is compatible with Ghost blog frame, as well as standard ways of doing graphics and illustrations.

### Twitter post covers

Must be the right dimensions, and have suitable . Here are some strong examples

<img width="581" alt="Screenshot 2019-04-23 at 08 13 54" src="https://user-images.githubusercontent.com/437292/57554280-540abf80-7371-11e9-9ba2-3ee42b3dfa6f.png">

<img width="517" alt="Screenshot 2019-04-22 at 06 47 56" src="https://user-images.githubusercontent.com/437292/57554317-6ab11680-7371-11e9-83d6-390cbd49a45d.png">

<img width="581" alt="Screenshot 2019-04-23 at 08 13 54" src="https://user-images.githubusercontent.com/437292/57554300-5c62fa80-7371-11e9-9eb4-5736ea59acf4.png">

## Twitter account cover

Here are some nice examples

- https://twitter.com/coinbase
- https://twitter.com/tumblr
- https://twitter.com/Nike
- https://twitter.com/sketch

## Reddit branding

- Color scheme
- Top cover
- Backgroudn image

## Product subbranding system

We have multiple digital, and in the near future physical, products. We need a system of subbrands for each one, where makes them recognizable parts of the Joystream identity. For example, we currently have

- Pioneer: This is a web based application for talking to our blockchain
- Joyful: This is a native application which does the blockchain vlaidation
- Colossus: This is a native application you run in order to provide storage services

Each one needs proper branding, such as a logo set, etc.

**Comment by bwhm** [comment]
Just some small comments on the actual content. 

My biggest questions are listed below, and are mostly concerning the process itself.

1. Is this on @TomiNadratowski alone, or should we involve more people?
2. How involved will you be in the process.

I would like @TomiNadratowski and elpassion to give this a proper review, ask questions, and then present a formal document, including things like:
   * Specific SoW
   * CTR (budget)
   * Milestones
   * Workflow (including how much this will require our involvement)

## Comments

> Jsgenesis.com footer

A brush up of this page could arguably be prioritized over this, as a couple of days should be sufficient.

> Email newsletter email capture screen

I would add template(s) for newsletters as a an extra deliverable.

> Lack of explicit rules for images and photographies

One of the few points I disagree with. I think it makes sense to try and formalize recurring and more serious posts, but I think some posts can be more informal in nature. In the specific case you are referring too, I do agree we should still avoid mixing between the "sudo" image (which is _somewhat_ consistent with our usual posts, eg. produced in house, transparent background, council members, etc) and the memes. If you prefer, we could separate such posts out to a more fitting medium.

> Blog covers

Something we've discussed before, and I fully support. Would cut down on production time, and improve quality.

> Blog images

(Somewhat related to "Lack of explicit rules for images and photographies".) 
I don't know what your point, or solution is here. I would argue reusing images helps readers recognize and associate images with whatever they are representing. For "recurring" posts, I think this is a good thing. 
As a sidenote, we need to break the text of posts sometimes. I don't think we can justify making new images, in sufficient quality, that is following the rules 2-5 times pr post. In addition to resources spent, it always causes delays.

> Deliverables

[Dead link](https://issuu.com/joaodiogo/docs/frv-brand-guidelines-_final_)
Are the examples meant to represent good branding, or good branding style guides?

> Communication templates

I would argue for more blog categories, but it's fine to start with these.

> Product subbranding system

This seems premature, maybe with the exception of `Pioneer`. Most users don't see anything else.

**Comment by bedeho** [comment]
Identity itself is done, will be introduced into this repo later.
